image: python:latest

pipelines:
  branches:
    master:
      - step:
          caches:
            - pip
          script:
            - pipe: atlassian/pypi-publish:latest
              variables:
                PYPI_USERNAME: $PYPI_USERNAME
                PYPI_PASSWORD: $PYPI_PASSWORD
                # REPOSITORY: '<string>' # Optional.
                DISTRIBUTIONS: 'sdist bdist_wheel' # Optional.
                # FOLDER: '<string>' # Optional.
                # DEBUG: '<boolean>' # Optional.
