image: python:3.8

pipelines:
  branches:
    master:
      - step:
          script:
            - pipe: atlassian/pypi-publish:0.3.0
              variables:
                PYPI_USERNAME: $PYPI_USERNAME
                PYPI_PASSWORD: $PYPI_PASSWORD
                # REPOSITORY: '<string>' # Optional.
                # DISTRIBUTIONS: '<string>' # Optional.
                # FOLDER: '<string>' # Optional.
                # DEBUG: '<boolean>' # Optional.
